apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: n6-2001-numa1p0-pf3
  annotations:
    k8s.v1.cni.cncf.io/resourceName: kinara.com/bmn-mlx-sriov-pf3
spec:
  config: '{
  "type": "sriov",
  "cniVersion": "0.3.1",
  "name": "sriov-network",
  "vlan": 2001,
  "logLevel": "debug",
  "ipam": {
        "type": "whereabouts",
        "range": "169.30.3.0/24",
        "exclude": [
            "169.30.3.1/32",
            "169.30.3.254/32"
            ]
      }
}'